<?php

# Class implementing the Campop online atlas
class populationspast extends onlineAtlas
{
	# Function to assign defaults additional to the general application defaults
	public function defaults ()
	{
		# Define unavailable datasets for one group of supplied data
		$unavailable2026datasets = array (1851);
		
		# Add implementation defaults
		$defaults = array (
			
			// Application name
			'applicationName' => 'Populations Past atlas',
			
			// Datasets
			'years' => array (1851, 1861, 1871, 1881, 1891, 1901, 1911),
			
			// Sources, so that different geometries can be used; these are referenced as 'source' in the layer definitions below, indexed from 0 (e.g. 1 means 2nd source)
			'sources' => 2,
			
			// Area names
			'areaNameField' => 'SUBDIST',
			'areaNameFallbackField' => 'REGDIST',
			
			// First run message
			'firstRunMessageHtml' =>
				  '<p><strong>Welcome to Populations Past, from CAMPOP</strong></p>'
				. '<p>Populationspast.org, the Atlas of Victorian and Edwardian Population, enables you to explore demographic changes from 1851-1911.</p>'
				. '<p>Please note that various improvements are still being made to the site.</p>',
			
			// About page
			'aboutFile' => $_SERVER['DOCUMENT_ROOT'] . '/about/index.html',
			
			// Geocoder
			'geocoderApiKey' => NULL,		// Obtain at https://www.cyclestreets.net/api/apply/
			
			// CSV downloads
			'downloadFilenameBase' => 'populationspast',
			'downloadInitialNotice' => "This data has been produced by the 'Atlas of Victorian Fertility Decline' project (PI: A.M. Reid) with funding from the ESRC (ES/L015463/1), using an enhanced version of data from Schürer, K. and Higgs, E. (2014). Integrated Census Microdata (I-CeM), 1851-1911. [data collection]. Colchester, Essex: UK Data Archive [distributor]. SN: 7481, https://doi.org/10.5255/UKDA-SN-7481-1. Citation details: please see https://www.populationspast.org/acknowledgements/ .",	// This is only used when importing the data, not dynamically
			
			// Unknown values
			'valueUnknown' => 'NULL',
			'colourUnknown' => false,
			
			// Fields
			'expandableHeadings' => true,
			'defaultField' => 'IMR',
			'fields' => array (
				
				// General fields
				'year' => array (
					'label' => 'Year',
					'description' => 'Year',
					'intervals' => '',
					'general' => true,
				),
				'REGDIST' => array (
					'label' => 'Registration district',
					'description' => 'Registration district',
					'intervals' => '',
					'general' => true,
				),
				'SUBDIST' => array (
					'label' => 'Sub-district',
					'description' => 'Sub-district',
					'intervals' => '',
					'general' => true,
				),
				'POP' => array (
					'label' => 'Population',
					'description' => 'Population',
					'intervals' => '',
					'general' => true,
				),
				'ACRES' => array (
					'label' => 'Acreage',
					'description' => 'Acreage',
					'intervals' => '',
					'general' => true,
				),
				
				'_' => array (
					'label' => '[Show background map only]',
					'description' => 'Removes data from the map, showing only the background',
					'intervals' => '',
				),
				'POP_DENS' => array (
					'label' => 'Population density',
					'description' => 'The number of people per acre',
					'intervals' => '<1, 1 - <5, 5 - <50, 50 - <100, 100 - <200, 200 - <300, ≥300',
				),
				'TYPE' => array (
					'label' => 'Type of place',
					'description' => 'Type of place',
					'intervals' => array (
						'agriculture'		=> '#74b273',
						'semi-rural'		=> '#d2ffbe',
						'professional'		=> '#0071fe',
						'semi-professional'	=> '#bee8ff',
						'mining'			=> '#cd6667',
						'textile'			=> '#aa66cd',
						'transport'			=> '#ffaa01',
						'other urban'		=> '#b2b2b2',
					),
				),
				// Population (POP) for download only
				// Acres (ACRES) for download only
				
				'TFR' => array (
					'label' => 'Total Fertility Rate',
					'description' => 'The average number of children per woman',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, ≥7',
					'grouping' => 'Fertility',
				),
				'TMFR' => array (
					'label' => 'Total Marital Fertility Rate',
					'description' => 'The average number of children per married woman',
					'intervals' => '<5, 5 - <6, 6 - <7, 7 - <8, 8 - <9, 9 - <10, ≥10',
					'grouping' => 'Fertility',
				),
				'LEGIT_RATE' => array (
					'label' => 'Legitimate birth rate',
					'description' => 'The number of legitimate births per 1,000 married women',
					'intervals' => '<150, 150 - <175, 175 - <200, 200 - <225, 225 - <250, 250 - <275, ≥275',
					'grouping' => 'Fertility',
				),
				'ILEG_RATE' => array (
					'label' => 'Illegitimate birth rate',
					'description' => 'The number of illegitimate births per 1,000 unmarried women',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Fertility',
				),
				'ILEG_RATIO' => array (
					'label' => 'Illegitimacy Ratio',
					'description' => 'The number of illegitimate births per 100 total births',
					'intervals' => '<3, 3 - <6, 6 - <9, 9 - <12, 12 - <15, 15 - <18, ≥18',
					'grouping' => 'Fertility',
				),
				
				'F_SMAM' => array (
					'label' => 'Age at marriage (female)',
					'description' => 'The average age at marriage for women',
					'intervals' => '<25, 25 - <26, 26 - <27, 27 - <28, 28 - <29, 29 - <30, ≥30',
					'grouping' => 'Marriage',
				),
				'M_SMAM' => array (
					'label' => 'Age at marriage (male)',
					'description' => 'The average age at marriage for men',
					'intervals' => '<25, 25 - <26, 26 - <27, 27 - <28, 28 - <29, 29 - <30, ≥30',
					'grouping' => 'Marriage',
				),
				'F_CEL_4554' => array (
					'label' => 'Celibacy (women)',
					'description' => 'Never-married women as a percentage of all women aged 45 to 54',
					'intervals' => '<5, 5 - <7, 7 - <9, 9 - <11, 11 - <13, 13 - <15, ≥15',
					'grouping' => 'Marriage',
				),
				'M_CEL_4554' => array (
					'label' => 'Celibacy (men)',
					'description' => 'Never-married men as a percentage of all men aged 45 to 54',
					'intervals' => '<5, 5 - <7, 7 - <9, 9 - <11, 11 - <13, 13 - <15, ≥15',
					'grouping' => 'Marriage',
				),
				
				'DOC' => array (
					'label' => 'Doctors per 10k people',
					'description' => 'The number of doctors per 10,000 people',
					'intervals' => '<2, 2 - <4, 4 - <6, 6 - <8, 8 - <10, 10 - <12, ≥12',
					'grouping' => 'Mortality and health',
				),
				'IMR' => array (
					'label' => 'Infant Mortality Rate',
					'description' => 'The number of children out of 1,000 born who died before their first birthday',
					'intervals' => '<60, 60 - <80, 80 - <110, 110 - <140, 140 - <160, 160 - <180, ≥180',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
				),
				'ECMR' => array (
					'label' => 'Early Childhood Mortality Rate',
					'description' => 'The number of children dying out of 1,000 children aged 1 to 5',
					'intervals' => '<20, 20 - <40, 40 - <60, 60 - <80, 80 - <100, 100 - <120, ≥120',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
				),
				'SP_FAM' => array (
					'label' => 'Lone parent households',
					'description' => 'Households containing a lone-parent family, as a percentage of all households',
					'intervals' => '<2.5, 2.5 - <4, 4 - <5.5, 5.5 - <7.0, 7.0 - <8.5, 8.5 - <10, ≥10',
					'grouping' => 'Households',
				),
				'SINGLE_PER' => array (
					'label' => 'Single person households',
					'description' => 'Households containing just one person, as a percentage of all households',
					'intervals' => '<3, 3 - <5, 5 - <7, 7 - <9, 9 - <11, 11 - <13, ≥13',
					'grouping' => 'Households',
				),
				'BOARD' => array (
					'label' => 'Households with boarders',
					'description' => 'Households containing at least one boarder, as a percentage of all households',
					'intervals' => '<3, 3 - <6, 6 - <9, 9 - <12, 12 - <15, 15 - <18, ≥18',
					'grouping' => 'Households',
				),
				'HH_KIN' => array (
					'label' => 'Households with kin',
					'description' => 'Households containing people related to the head but not his/her immediate family, as percentage of all households',
					'intervals' => '<10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, 30 - <35, ≥35',
					'grouping' => 'Households',
				),
				'HOUSE_SERV' => array (
					'label' => 'Households with live-in servants',
					'description' => 'Households containing at least one live-in servant, as a percentage of all households',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Households',
				),
				
				'DEPEND' => array (
					'label' => 'Dependency ratio',
					'description' => 'The number of dependents (children and elderly) per 100 working-age people',
					'intervals' => '<45, 45 - <50, 50 - <55, 55 - <60, 60 - <65, 65 - <70, ≥70',
					'grouping' => 'Age structure',
				),
				'C_WORK_AGE' => array (
					'label' => 'Child dependency ratio',
					'description' => 'The number of children per 100 working-age people',
					'intervals' => '<35, 35 - <40, 40 - <45, 45 - <50, 50 - <55, 55 - <60, ≥60',
					'grouping' => 'Age structure',
				),
				'ELD_WORK_A' => array (
					'label' => 'Old age dependency ratio',
					'description' => 'The number of elderly people per 100 working-age people',
					'intervals' => '<4, 4 - <6, 6 - <8, 8 - <10, 10 - <12, 12 - <14, ≥14',
					'grouping' => 'Age structure',
				),
				'AV_AGE' => array (
					'label' => 'Average age',
					'description' => 'Average (mean) age of the population',
					'intervals' => '<24, 24 - <26, 26 - <28, 28 - <30, 30 - <32, 32 - <34, ≥34',
					'grouping' => 'Age structure',
				),
				'AV_AGE_F' => array (
					'label' => 'Average age for women',
					'description' => 'Average (mean) age of the female population',
					'intervals' => '<24, 24 - <26, 26 - <28, 28 - <30, 30 - <32, 32 - <34, ≥34',
					'grouping' => 'Age structure',
				),
				'AV_AGE_M' => array (
					'label' => 'Average age for men',
					'description' => 'Average (mean) age of the male population',
					'intervals' => '<24, 24 - <26, 26 - <28, 28 - <30, 30 - <32, 32 - <34, ≥34',
					'grouping' => 'Age structure',
				),
				
				'SR' => array (
					'label' => 'Sex ratio',
					'description' => 'Number of working-age men per 100 working-age women',
					'intervals' => '<75, 75 - <85, 85 - <95, 95 - <105, 105 - <115, 115 - <125, ≥125',
					'grouping' => 'Migration',
				),
				
				'LTM_10_F' => array (
					'label' => 'Women born <10km away',
					'description' => 'Women born <10km away from the place they were living as a percentage of all women',
					'intervals' => '<30, 30 - <40, 40 - <50, 50 - <60, 60 - <70, 70 - <80, ≥80',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'LTM_10_M' => array (
					'label' => 'Men born <10km away',
					'description' => 'Men born <10km away from the place they were living as a percentage of all men',
					'intervals' => '<30, 30 - <40, 40 - <50, 50 - <60, 60 - <70, 70 - <80, ≥80',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'LTM_1050_F' => array (
					'label' => 'Women born 10-49km away',
					'description' => 'Women born 10-49km away from the place they were living as a percentage of all women',
					'intervals' => '<10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, 30 - <35, ≥35',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'LTM_1050_M' => array (
					'label' => 'Men born 10-49km away',
					'description' => 'Men born 10-49km away from the place they were living as a percentage of all men',
					'intervals' => '<10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, 30 - <35, ≥35',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'LTM_50_F' => array (
					'label' => 'Women born >50km away',
					'description' => 'Women born ≥50km away from the place they were living as a percentage of all women',
					'intervals' => '<2, 2 - <5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, ≥25',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'LTM_50_M' => array (
					'label' => 'Men born >50km away',
					'description' => 'Men born ≥50km away from the place they were living as a percentage of all men',
					'intervals' => '<2, 2 - <5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, ≥25',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'IRL_F' => array (
					'label' => 'Women born in Ireland',
					'description' => 'Women born in Ireland as a percentage of all women',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'IRL_M' => array (
					'label' => 'Men born in Ireland',
					'description' => 'Men born in Ireland as a percentage of all men',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'SCT_F' => array (
					'label' => 'Women born in Scotland',
					'description' => 'Women born in Scotland as a percentage of all women',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'SCT_M' => array (
					'label' => 'Men born in Scotland',
					'description' => 'Men born in Scotland as a percentage of all men',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'ENG_F' => array (
					'label' => 'Women born in England',
					'description' => 'Women born in England as a percentage of all women',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'ENG_M' => array (
					'label' => 'Men born in England',
					'description' => 'Men born in England as a percentage of all men',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'WAL_F' => array (
					'label' => 'Women born Wales',
					'description' => 'Women born in Wales as a percentage of all women',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'WAL_M' => array (
					'label' => 'Men born in Wales',
					'description' => 'Men born in Wales as a percentage of all men',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'FOREIGN_F' => array (
					'label' => 'Women born overseas',
					'description' => 'Women born in overseas as a percentage of all women',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'FOREIGN_M' => array (
					'label' => 'Men born overseas',
					'description' => 'Men born in overseas as a percentage of all men',
					'intervals' => '<0.4, 0.4 - <0.8, 0.8 - <1.5, 1.5 - <2, 2 - <3, 3 - <5, ≥5',
					'grouping' => 'Migration',
					'subgroup' => 'Lifetime migration',
				),
				
				'HC1' => array (
					'label' => 'SES 1: non-manual high skilled',
					'description' => 'Non-manual high skilled men as a percentage of all working-age men',
					'intervals' => '<1, 1 - <2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, ≥6',
					'grouping' => 'Socio-economic status',
				),
				'HC2' => array (
					'label' => 'SES 2: non-manual low skilled',
					'description' => 'Non-manual medium or lower skilled men as a percentage of all working-age men',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Socio-economic status',
				),
				'HC3' => array (
					'label' => 'SES 3: manual high skilled',
					'description' => 'Manual high or medium skilled men as a percentage of all working-age men',
					'intervals' => '<20, 20 - <25, 25 - <30, 30 - <35, 35 - <40, 40 - <45, ≥45',
					'grouping' => 'Socio-economic status',
				),
				'HC4' => array (
					'label' => 'SES 4: manual low skilled',
					'description' => 'Manual lower skilled men as a percentage of all working-age men',
					'intervals' => '<10, 10 - <20, 20 - <30, 30 - <40, 40 - <50, 50 - <60, ≥60',
					'grouping' => 'Socio-economic status',
				),
				'HC5' => array (
					'label' => 'SES 5: manual unskilled',
					'description' => 'Manual unskilled men as a percentage of all working-age men',
					'intervals' => '<20, 20 - <30, 30 - <40, 40 - <50, 50 - <60, 60 - <70, ≥70',
					'grouping' => 'Socio-economic status',
				),
				'SC1' => array (
					'label' => "RG's class 1: professional",
					'description' => "RG's social class 1 (professional and managerial workers) as a percentage of all working-age men",
					'intervals' => '<1.5, 1.5 - <3, 3 - <4.5, 4.5 - <6, 6 - <7.5, 7.5 - <9, ≥9',
					'grouping' => 'Social class - RG',
				),
				'SC2' => array (
					'label' => "RG's class 2: non-manual skilled",
					'description' => "RG's social class 2 (skilled non-manual workers) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC3' => array (
					'label' => "RG's class 3: manual skilled",
					'description' => "RG's social class 3 (skilled workmen) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC4' => array (
					'label' => "RG's class 4: manual semi-skilled",
					'description' => "RG's social class 4 (semi-skilled workmen) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC5' => array (
					'label' => "RG's class 5: manual unskilled",
					'description' => "RG's social class 5 (unskilled workmen) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC6' => array (
					'label' => "RG's class 6: textile workers",
					'description' => "RG's social class 6 (textile workers) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC7' => array (
					'label' => "RG's class 7: miners",
					'description' => "RG's social class 7 (miners) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				'SC8' => array (
					'label' => "RG's class 8: agricultural labourers",
					'description' => "RG's social class 8 (agricultural labourers) as a percentage of all working-age men",
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => 'Social class - RG',
				),
				
				'FMAR_PRATE' => array (
					'label' => 'Married women working',
					'description' => 'Married women working as a percentage of all married women',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => "Women's work",
				),
				'FNM_PRATE' => array (
					'label' => 'Single women working',
					'description' => 'Single women working as a percentage of all single women',
					'intervals' => '<40, 40 - <50, 50 - <60, 60 - <70, 70 - <80, 80 - <90, ≥90',
					'grouping' => "Women's work",
				),
				'FWID_PRATE' => array (
					'label' => 'Widowed women working',
					'description' => 'Widowed women working as a percentage of all widowed women',
					'intervals' => '<40, 40 - <50, 50 - <60, 60 - <70, 70 - <80, 80 - <90, ≥90',
					'grouping' => "Women's work",
				),
				'F_DOM' => array (
					'label' => 'Domestic servants (women)',
					'description' => 'Domestic servants as a percentage of all employed working-age women',
					'intervals' => '<10, 10 - <20, 20 - <30, 30 - <40, 40 - <50, 50 - <60, ≥60',
					'grouping' => "Women's work",
				),
				'F_TEX' => array (
					'label' => 'Textile workers (female)',
					'description' => 'Textile workers as a percentage of all employed working-age women',
					'intervals' => '<1, 1 - <5, 5 - <10, 10 - <20, 20 - <30, 30 - <40, ≥40',
					'grouping' => "Women's work",
				),
				
				'C_TEACHER' => array (
					'label' => 'Children per teacher',
					'description' => 'Number of children per teacher',
					'intervals' => '<25, 25 - <50, 50 - <75, 75 - <100, 100 - <125, 125 - <150, ≥150',
					'grouping' => "Children's work and schooling",
				),
				'F_CL_1013' => array (
					'label' => 'Girls aged 10-13 working',
					'description' => 'Number of girls in employment as a percentage of all girls aged 10-13',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => "Children's work and schooling",
				),
				'M_CL_1013' => array (
					'label' => 'Boys aged 10-13 working',
					'description' => 'Number of boys in employment as a percentage of all boys aged 10-13',
					'intervals' => '<5, 5 - <10, 10 - <15, 15 - <20, 20 - <25, 25 - <30, ≥30',
					'grouping' => "Children's work and schooling",
				),
				'F_CL_1418' => array (
					'label' => 'Girls aged 14-18 working',
					'description' => 'Number of girls in employment as a percentage of all girls aged 14-18',
					'intervals' => '<20, 20 - <25, 25 - <30, 30 - <35, 35 - <40, 40 - <45, ≥45',
					'grouping' => "Children's work and schooling",
				),
				'M_CL_1418' => array (
					'label' => 'Boys aged 14-18 working',
					'description' => 'Number of boys in employment as a percentage of all boys aged 14-18',
					'intervals' => '<20, 20 - <25, 25 - <30, 30 - <35, 35 - <40, 40 - <45, ≥45',
					'grouping' => "Children's work and schooling",
				),
				
/*
				'conrd_town' => array (
					'label' => 'Consistent Registration District',
					'grouping' => 'Identifiers',
					'subgroup' => 'Identifiers',
				),
				'acres' => array (
					'label' => 'Acreage ',
					'description' => 'Acreage of the consistent geography (conrd_town) unit',
					'grouping' => 'Identifiers',
					'subgroup' => 'Identifiers',
				),
				'conrdname' => array (
					'label' => 'Registration Districts within conrd',
					'description' => 'as defined in published census volume',
					'grouping' => 'Identifiers',
					'subgroup' => 'Identifiers',
				),
				'decade' => array (
					'label' => 'Decade',
					'description' => 'In PopulationsPast figures for decades are displayed against the census year ending that decade',
					'grouping' => 'Identifiers',
					'subgroup' => 'Identifiers',
				),
*/
				'LT0' => array (
					'label' => 'Life expectancy at birth',
					'description' => 'The age which a newborn baby can be expected to live to, given prevailing mortality rates',
					'intervals' => '<41, 41 - <44, 44 - <47, 47 - <49, 49 - <50, 50 - <53, ≥53',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Life expectancy',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'LT0F' => array (
					'label' => 'Female life expectancy at birth',
					'description' => 'The age which a newborn baby girl can be expected to live to, given prevailing female mortality rates',
					'intervals' => '<41, 41 - <44, 44 - <47, 47 - <49, 49 - <50, 50 - <53, ≥53',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Life expectancy',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'LT0M' => array (
					'label' => 'Male life expectancy at birth',
					'description' => 'The age which a newborn baby boy can be expected to live to, given prevailing male mortality rates',
					'intervals' => '<41, 41 - <44, 44 - <47, 47 - <49, 49 - <50, 50 - <53, ≥53',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Life expectancy',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR14F' => array (
					'label' => 'Female mortality age 1-4',
					'description' => 'Age specific mortality rate for females aged 1-4 in the area',
					'intervals' => '<9, 9 - <12, 12 - <15, 15 - <18, 18 - <22, 22 - <30, ≥30',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR14M' => array (
					'label' => 'Male mortality age 1-4',
					'description' => 'Age specific mortality rate for males aged 1-4 in the area',
					'intervals' => '<9, 9 - <12, 12 - <15, 15 - <18, 18 - <23, 23 - <30, ≥30',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR514' => array (
					'label' => 'Mortality age 5-14',
					'description' => 'Age specific mortality rate for people aged 5-14',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, ≥7',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR514F' => array (
					'label' => 'Female mortality age 5-14',
					'description' => 'Age specific mortality rate for females aged 5-14 in the area',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, ≥7',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR514M' => array (
					'label' => 'Male mortality age 5-14',
					'description' => 'Age specific mortality rate for males aged 5-14 in the area',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, ≥7',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR1544' => array (
					'label' => 'Mortality age 15-44',
					'description' => 'Age specific mortality rate for people aged 15-44 in the area',
					'intervals' => '<5, 5 - <6, 6 - <7, 7 - <8, 8 - <8, 8 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR1544F' => array (
					'label' => 'Female mortality age 15-44',
					'description' => 'Age specific mortality rate for females aged 15-44 in the area',
					'intervals' => '<5, 5 - <6, 6 - <7, 7 - <8, 8 - <9, 9 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR1544M' => array (
					'label' => 'Male mortality age 15-44',
					'description' => 'Age specific mortality rate for males aged 15-44 in the area',
					'intervals' => '<5, 5 - <6, 6 - <7, 7 - <8, 8 - <9, 9 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR4564' => array (
					'label' => 'Mortality age 45-64',
					'description' => 'Age specific mortality rate for people aged 45-64 in the area',
					'intervals' => '<14, 14 - <16, 16 - <17, 17 - <18, 18 - <20, 20 - <24, ≥24',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR4564F' => array (
					'label' => 'Female mortality age 45-64',
					'description' => 'Age specific mortality rate for females aged 45-64 in the area',
					'intervals' => '<14, 14 - <16, 16 - <17, 17 - <18, 18 - <20, 20 - <24, ≥24',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR4564M' => array (
					'label' => 'Male mortality age 45-64',
					'description' => 'Age specific mortality rate for males aged 45-64 in the area',
					'intervals' => '<14, 14 - <16, 16 - <17, 17 - <18, 18 - <20, 20 - <24, ≥24',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR65' => array (
					'label' => 'Mortality age >=65',
					'description' => 'Age specific mortality rate for people aged >=65 in the area',
					'intervals' => '<76, 76 - <80, 80 - <83, 83 - <86, 86 - <90, 90 - <95, ≥95',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR65F' => array (
					'label' => 'Female mortality age >=65',
					'description' => 'Age specific mortality rate for females aged >=65 in the area',
					'intervals' => '<76, 76 - <80, 80 - <83, 83 - <86, 86 - <90, 90 - <95, ≥95',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'ASMR65M' => array (
					'label' => 'Male mortality age >=65',
					'description' => 'Age specific mortality rate for males aged >=65 in the area',
					'intervals' => '<76, 76 - <80, 80 - <83, 83 - <86, 86 - <90, 90 - <95, ≥95',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Age-specific mortality',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'CIR0100' => array (
					'label' => 'Circulatory disease mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from circulatory disease (heart diseases and strokes) per 10,000 people in the area',
					'intervals' => '<7, 7 - <11, 11 - <13, 13 - <15, 15 - <17, 17 - <20, ≥20',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Circulatory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'CIR1544' => array (
					'label' => 'Circulatory disease mortality age 15-44',
					'labelShort' => 'Age 15-44',
					'description' => 'Number of deaths aged 15-44 from circulatory disease (heart diseases and strokes) per 10,000 people aged 15-44 in the area',
					'intervals' => '<2, 2 - <4, 4 - <5, 5 - <6, 6 - <7, 7 - <8, ≥8',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Circulatory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'CIR4564' => array (
					'label' => 'Circulatory disease mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths aged 45-64 from circulatory disease (heart diseases and strokes) per 10,000 people aged 45-64 in the area',
					'intervals' => '<10, 10 - <21, 21 - <27, 27 - <30, 30 - <35, 35 - <40, ≥40',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Circulatory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'CIR65' => array (
					'label' => 'Circulatory disease mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths aged >=65 from circulatory disease (heart diseases and strokes) per 10,000 people aged >=65 in the area',
					'intervals' => '<42, 42 - <80, 80 - <98, 98 - <113, 113 - <129, 129 - <155, ≥155',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Circulatory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG0100' => array (
					'label' => 'Diarrhoeal and digestive disease mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from diarrhoeal disease (diarrhoea, enteritis, cholera, typhoid, bowel hives etc) per 10,000 people in the area',
					'intervals' => '<12, 12 - <14, 14 - <16, 16 - <18, 18 - <21, 21 - <24, ≥24',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIGIMR' => array (
					'label' => 'Diarrhoeal and digestive disease mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from diarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 1000 infants born in the area',
					'intervals' => '<7, 7 - <10, 10 - <13, 13 - <16, 16 - <20, 20 - <25, ≥25',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG14' => array (
					'label' => 'Diarrhoeal and digestive  disease mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths aged 1-4 from diarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 10,000 people aged 1-4 in the area',
					'intervals' => '<7, 7 - <11, 11 - <14, 14 - <18, 18 - <23, 23 - <34, ≥34',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG514' => array (
					'label' => 'Diarrhoeal and digestive  disease mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from diarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 10,000 people aged 5-14 in the area',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 5 - <7, ≥7',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG1544' => array (
					'label' => 'Diarrhoeal and digestive  disease mortality age 15-44',
					'labelShort' => 'Age 15-44',
					'description' => 'Number of deaths aged 15-44 from diarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 10,000 people aged 15-44 in the area',
					'intervals' => '<4, 4 - <5, 5 - <6, 6 - <7, 7 - <8, 8 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG4564' => array (
					'label' => 'Diarrhoeal and digestive  disease mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths aged 45-64 from diarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 10,000 people aged 45-64 in the area',
					'intervals' => '<13, 13 - <17, 17 - <20, 20 - <22, 22 - <25, 25 - <30, ≥30',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'DIADIG65' => array (
					'label' => 'Diarrhoeal and digestive  disease mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths aged >=65 fromdiarrhoeal (diarrhoea, enteritis, cholera, typhoid, bowel hives etc)  and digestive disease (diseases of the digestive system, including liver and pancreas) per 10,000 people aged >=65 in the area',
					'intervals' => '<37, 37 - <45, 45 - <53, 53 - <62, 62 - <72, 72 - <86, ≥86',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Diarrhoeal/digestive',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'GEN0100' => array (
					'label' => 'Genitourinary disease mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from genitourinary disease (diseases of the genitourinary system, including kidney, bladder and genital organs) per 10,000 people in the area',
					'intervals' => '<1, 1 - <2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, ≥6',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Genitourinary',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'GEN1544' => array (
					'label' => 'Genitourinary disease mortality age 15-44',
					'labelShort' => 'Age 15-44',
					'description' => 'Number of deaths age 15-44 from genitourinary disease (diseases of the genitourinary system, including kidney, bladder and genital organs) per 10,000 people age 15-44 in the area',
					'intervals' => '<1, 1 - <2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, ≥6',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Genitourinary',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'GEN4564' => array (
					'label' => 'Genitourinary disease mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths age 45-49 from genitourinary disease (diseases of the genitourinary system, including kidney, bladder and genital organs) per 10,000 people age 45-49 in the area',
					'intervals' => '<3, 3 - <5, 5 - <6, 6 - <7, 7 - <9, 9 - <11, ≥11',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Genitourinary',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'GEN65' => array (
					'label' => 'Genitourinary disease mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths age >=65 from genitourinary disease (diseases of the genitourinary system, including kidney, bladder and genital organs) per 10,000 people age >=65 in the area',
					'intervals' => '<7, 7 - <15, 15 - <19, 19 - <23, 23 - <28, 28 - <34, ≥34',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Genitourinary',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'INF0100' => array (
					'label' => 'Infectious disease mortality ',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from infectious diseases (any bacterial or viral infectious disease) per 10,000 people in the area',
					'intervals' => '<7, 7 - <9, 9 - <11, 11 - <14, 14 - <21, 21 - <29, ≥29',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Infectious disease',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'INFIMR' => array (
					'label' => 'Infectious disease mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from infectious diseases (any bacterial or viral infectious disease) per 1000 infants born in the area',
					'intervals' => '<5, 5 - <7, 7 - <8, 8 - <9, 9 - <11, 11 - <14, ≥14',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Infectious disease',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'INF14' => array (
					'label' => 'Infectious disease mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths age 1-4 from infectious diseases (any bacterial or viral infectious disease) per 10,000 people age 1-4 in the area',
					'intervals' => '<26, 26 - <37, 37 - <49, 49 - <63, 63 - <82, 82 - <113, ≥113',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Infectious disease',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'INF514' => array (
					'label' => 'Infectious disease mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from infectious diseases (any bacterial or viral infectious disease) per 10,000 people aged 5-14 in the area',
					'intervals' => '<5, 5 - <7, 7 - <9, 9 - <12, 12 - <18, 18 - <27, ≥27',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Infectious disease',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NEO0100' => array (
					'label' => 'Cancer mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from cancer per 10,000 people in the area',
					'intervals' => '<4, 4 - <5, 5 - <6, 6 - <8, 8 - <9, 9 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Cancer',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NEO4564' => array (
					'label' => 'Cancer mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths age 45-64 from cancer per 10,000 people age 45-64 in the area',
					'intervals' => '<10, 10 - <13, 13 - <16, 16 - <19, 19 - <22, 22 - <25, ≥25',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Cancer',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NEO65' => array (
					'label' => 'Cancer mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths age >=65 from cancer per 10,000 people age >=65 in the area',
					'intervals' => '<19, 19 - <26, 26 - <33, 33 - <41, 41 - <51, 51 - <63, ≥63',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Cancer',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES0100' => array (
					'label' => 'Respiratory disease mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people in the area',
					'intervals' => '<19, 19 - <22, 22 - <25, 25 - <28, 28 - <32, 32 - <37, ≥37',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RESIMR' => array (
					'label' => 'Respiratory disease mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 1000 infants born in the area',
					'intervals' => '<12, 12 - <16, 16 - <19, 19 - <22, 22 - <25, 25 - <29, ≥29',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES14' => array (
					'label' => 'Respiratory disease mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths age 1-4 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people age 1-4 in the area',
					'intervals' => '<24, 24 - <34, 34 - <41, 41 - <49, 49 - <62, 62 - <83, ≥83',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES514' => array (
					'label' => 'Respiratory disease mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people aged 5-14 in the area',
					'intervals' => '<1, 1 - <2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, ≥6',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES1544' => array (
					'label' => 'Respiratory disease mortality age 15-44',
					'labelShort' => 'Age 15-44',
					'description' => 'Number of deaths aged 15-44 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people aged 15-44 in the area',
					'intervals' => '<3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, 7 - <9, ≥9',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES4564' => array (
					'label' => 'Respiratory disease mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths aged 45-64 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people aged 45-64 in the area',
					'intervals' => '<16, 16 - <21, 21 - <25, 25 - <29, 29 - <35, 35 - <48, ≥48',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'RES65' => array (
					'label' => 'Respiratory disease mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths aged >=65 from respiratory disease (bronchitis, pneumonia and other lung conditions) per 10,000 people aged >=65 in the area',
					'intervals' => '<75, 75 - <95, 95 - <111, 111 - <129, 129 - <151, 151 - <187, ≥187',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Respiratory',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB0100' => array (
					'label' => 'Tuberculosis mortality',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from tuberculosis (all forms) per 10,000 people in the area',
					'intervals' => '<14, 14 - <17, 17 - <20, 20 - <23, 23 - <26, 26 - <31, ≥31',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUBIMR' => array (
					'label' => 'Tuberculosis mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from tuberculosis (all forms) per 1000 infants born in the area',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <6, 6 - <7, 7 - <10, ≥10',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB14' => array (
					'label' => 'Tuberculosis mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths age 1-4 from tuberculosis (all forms) per 10,000 people age 1-4 in the area',
					'intervals' => '<8, 8 - <12, 12 - <16, 16 - <20, 20 - <26, 26 - <38, ≥38',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB514' => array (
					'label' => 'Tuberculosis mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from tuberculosis (all forms) per 10,000 people aged 5-14 in the area',
					'intervals' => '<4, 4 - <6, 6 - <7, 7 - <8, 8 - <10, 10 - <14, ≥14',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB1524' => array (
					'label' => 'Tuberculosis mortality age 15-24',
					'labelShort' => 'Age 15-24',
					'description' => 'Number of deaths aged 15-44 from tuberculosis (all forms) per 10,000 people aged 15-24 in the area',
					'intervals' => '<14, 14 - <19, 19 - <23, 23 - <28, 28 - <33, 33 - <41, ≥41',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB2534' => array (
					'label' => 'Tuberculosis mortality age 25-34',
					'labelShort' => 'Age 25-34',
					'description' => 'Number of deaths aged 25-34 from tuberculosis (all forms)  per 10,000 people aged 25-34 in the area',
					'intervals' => '<19, 19 - <24, 24 - <29, 29 - <34, 34 - <40, 40 - <47, ≥47',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB3544' => array (
					'label' => 'Tuberculosis mortality age 35-44',
					'labelShort' => 'Age 35-44',
					'description' => 'Number of deaths aged 35-44 from tuberculosis (all forms) per 10,000 people aged 35-44 in the area',
					'intervals' => '<15, 15 - <20, 20 - <24, 24 - <29, 29 - <33, 33 - <40, ≥40',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB4564' => array (
					'label' => 'Tuberculosis mortality age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths aged 45-64 from tuberculosis (all forms) per 10,000 people aged 45-64 in the area',
					'intervals' => '<11, 11 - <15, 15 - <18, 18 - <22, 22 - <25, 25 - <31, ≥31',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'TUB65' => array (
					'label' => 'Tuberculosis mortality age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths aged >=65 from tuberculosis (all forms) per 10,000 people aged >=65 in the area',
					'intervals' => '<4, 4 - <7, 7 - <10, 10 - <12, 12 - <15, 15 - <21, ≥21',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Tuberculosis',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'VIO0100' => array (
					'label' => 'Mortality from external causes',
					'labelShort' => 'Overall',
					'description' => 'Number of deaths from external causes (accidents, violence and suicide) per 10,000 people in the area',
					'intervals' => '<3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, 7 - <8, ≥8',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: External causes',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'VIO1544' => array (
					'label' => 'Mortality from external causes age 15-44',
					'labelShort' => 'Age 15-44',
					'description' => 'Number of deaths from external causes (accidents, violence and suicide) per 10,000 people aged 15-44 in the area',
					'intervals' => '<2, 2 - <3, 3 - <4, 4 - <5, 5 - <6, 6 - <7, ≥7',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: External causes',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'VIO4564' => array (
					'label' => 'Mortality from external causes age 45-64',
					'labelShort' => 'Age 45-64',
					'description' => 'Number of deaths aged 45-64 from external causes (accidents, violence and suicide) per 10,000 people aged 45-64 in the area',
					'intervals' => '<4, 4 - <6, 6 - <7, 7 - <8, 8 - <9, 9 - <11, ≥11',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: External causes',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'VIO65' => array (
					'label' => 'Mortality from external causes age >=65',
					'labelShort' => 'Age ≥65',
					'description' => 'Number of deaths aged >=65 from external causes (accidents, violence and suicide) per 10,000 people aged >=65 in the area',
					'intervals' => '<6, 6 - <9, 9 - <11, 11 - <13, 13 - <16, 16 - <19, ≥19',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: External causes',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'MEAIMR' => array (
					'label' => 'Measles mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from measles per 1000 infants born in the area',
					'intervals' => '<0.5, 0.5 - <1, 1 - <1.5, 1.5 - <2, 2 - <2.5, 2.5 - <3, ≥3',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Measles',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'MEA14' => array (
					'label' => 'Measles mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths aged 1-4 from measles per 10,000 children aged 1-4 in the area',
					'intervals' => '<1, 1 - <6, 6 - <10, 10 - <15, 15 - <22, 22 - <33, ≥33',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Measles',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'MEA514' => array (
					'label' => 'Measles mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from measles per 10,000 children aged 5-14 in the area',
					'intervals' => '<0.5, 0.5 - <1, 1 - <1.5, 1.5 - <2, 2 - <2.5, 2.5 - <3, ≥3',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Measles',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'SF14' => array (
					'label' => 'Scarlet fever mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths aged 1-4 from scarlet fever per 10,000 children aged 1-4 in the area',
					'intervals' => '<1, 1 - <6, 6 - <10, 10 - <15, 15 - <22, 22 - <33, ≥33',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Scarlet fever',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'SF514' => array (
					'label' => 'Scarlet fever mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from scarlet fever per 10,000 children aged 5-14 in the area',
					'intervals' => '<1, 1 - <2, 2 - <3, 3 - <5, 5 - <8, 8 - <12, ≥12',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Scarlet fever',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'SMA14' => array (
					'label' => 'Small pox mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths aged 1-4 from small pox per 10,000 children aged 1-4 in the area',
					'intervals' => '<0.5, 0.5 - <1, 1 - <1.5, 1.5 - <2, 2 - <2.5, 2.5 - <3, ≥3',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Small pox',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'SMA514' => array (
					'label' => 'Small pox mortality age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Number of deaths aged 5-14 from small pox per 10,000 children aged 5-14 in the area',
					'intervals' => '<0.5, 0.5 - <1, 1 - <1.5, 1.5 - <2, 2 - <2.5, 2.5 - <3, ≥3',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Small pox',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'WHOIMR' => array (
					'label' => 'Whooping cough mortality age 0',
					'labelShort' => 'Age 0',
					'description' => 'Number of deaths aged 0 from whooping cough per 1000 infants born in the area',
					'intervals' => '<2, 2 - <4, 4 - <5, 5 - <6, 6 - <7, 7 - <8, ≥8',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Whooping cough',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'WHO14' => array (
					'label' => 'Whooping cough mortality age 1-4',
					'labelShort' => 'Age 1-4',
					'description' => 'Number of deaths aged 1-4 from whooping cough per 10,000 children aged 1-4 in the area',
					'intervals' => '<6, 6 - <10, 10 - <14, 14 - <17, 17 - <22, 22 - <31, ≥31',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Whooping cough',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'MMR1544' => array (
					'label' => 'Maternal mortality ratio',
					'description' => 'Number of deaths to women aged 15-44 during or following pregnancy or childbirth per 10,000 births in the area',
					'intervals' => '<21, 21 - <31, 31 - <37, 37 - <43, 43 - <49, 49 - <58, ≥58',
					'grouping' => 'Mortality and health',
					'subgroup' => 'Cause-specific: Maternal',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR' => array (
					'label' => 'Net migration rate',
					'labelShort' => 'Overall',
					'description' => 'Net population increase due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR514' => array (
					'label' => 'Net migration rate age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Net population increase in those aged 5-14 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRF514' => array (
					'label' => 'Female net migration rate age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Net population increase in females aged 5-14 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Female',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRM514' => array (
					'label' => 'Male net migration rate age 5-14',
					'labelShort' => 'Age 5-14',
					'description' => 'Net population increase in males aged 5-14 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Male',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR1524' => array (
					'label' => 'Net migration rate age 15-24',
					'labelShort' => 'Age 15-24',
					'description' => 'Net population increase in those aged 15-24 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRF1524' => array (
					'label' => 'Female net migration rate age 15-24',
					'labelShort' => 'Age 15-24',
					'description' => 'Net population increase in females aged 15-24 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Female',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRM1524' => array (
					'label' => 'Male net migration rate age 15-24',
					'labelShort' => 'Age 15-24',
					'description' => 'Net population increase in males aged 15-24 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Male',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR2534' => array (
					'label' => 'Net migration rate age 25-34',
					'labelShort' => 'Age 25-34',
					'description' => 'Net population increase in those aged 25-34 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRF2534' => array (
					'label' => 'Female net migration rate age 25-34',
					'labelShort' => 'Age 25-34',
					'description' => 'Net population increase in females aged 25-34 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Female',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRM2534' => array (
					'label' => 'Male net migration rate age 25-34',
					'labelShort' => 'Age 25-34',
					'description' => 'Net population increase in males aged 25-34 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Male',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR3544' => array (
					'label' => 'Net migration rate age 35-44',
					'labelShort' => 'Age 35-44',
					'description' => 'Net population increase in those aged 35-44 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRF3544' => array (
					'label' => 'Female net migration rate age 35-44',
					'labelShort' => 'Age 35-44',
					'description' => 'Net population increase in females aged 35-44 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Female',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRM3544' => array (
					'label' => 'Male net migration rate age 35-44',
					'labelShort' => 'Age 35-44',
					'description' => 'Net population increase in males aged 35-44 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Male',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMR4554' => array (
					'label' => 'Net migration rate age 45-54',
					'labelShort' => 'Age 45-64',
					'description' => 'Net population increase in those aged 45-54 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: both sexes combined',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRF4554' => array (
					'label' => 'Female net migration rate age 45-54',
					'labelShort' => 'Age 45-64',
					'description' => 'Net population increase in females aged 45-54 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Female',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
				'NMRM4554' => array (
					'label' => 'Male net migration rate age 45-54',
					'labelShort' => 'Age 45-64',
					'description' => 'Net population increase in males aged 45-54 in the first census due to migration, as a percentage of population',
					'intervals' => '<-20, -20 - <-15, -15 - <-5, -5 - <5, 5 - <15, 15 - <20, ≥20',
					'grouping' => 'Migration',
					'subgroup' => 'Net migration rate: Male',
					'unavailable' => $unavailable2026datasets,
					'source' => 1,
				),
			),
		);
		
		# Merge in the default defaults
		$defaults += parent::defaults ();
		
		# Return the defaults
		return $defaults;
	}
	
	
	# Additional initialisation
	public function main ()
	{
		# Determine the extended application (repository) directory
		$this->extendedApplicationRoot = dirname (__FILE__);
		
		# Set the exports directory
		$this->settings['exportsDirectory'] = "{$this->extendedApplicationRoot}/exports/";
		
		# Run base main
		parent::main ();
	}
}

?>
